"""Ask the installed FHE library what it can do, and write the answer down.

Run this first, and run it again after any dependency change. It produces
`docs/LIBRARY_CAPABILITIES.md` and `docs/capabilities.json`, which the README,
the dashboard and the limitations document all read from. Every capability claim
this project makes traces back to a line of output from this script.

    python scripts/probe_library.py
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.preflight import require_dependencies  # noqa: E402

require_dependencies(script="scripts/probe_library.py")

from src.crypto.backend import CKKSParams, RefreshKind  # noqa: E402
from src.crypto.capabilities import Capabilities, ProbeResult  # noqa: E402
from src.crypto.tenseal_backend import probe_tenseal  # noqa: E402

_SYMBOL = {
    ProbeResult.SUPPORTED: "yes",
    ProbeResult.UNSUPPORTED: "NO",
    ProbeResult.ERROR: "ERROR",
}


def render_markdown(caps: Capabilities) -> str:
    lines: list[str] = []
    add = lines.append
    add("# Library Capabilities (generated)")
    add("")
    add("**This file is generated by `scripts/probe_library.py`. Do not edit it by hand.**")
    add("")
    add(
        "Every row below is the result of calling the API and recording what happened. "
        "Nothing here is copied from documentation, and nothing this project claims about "
        "the cryptography is allowed to contradict it."
    )
    add("")
    add(f"- Generated: `{datetime.now(timezone.utc).isoformat(timespec='seconds')}`")
    add(f"- Library: **{caps.library}** version `{caps.library_version}`")
    add(f"- Scheme: **{caps.scheme}**")
    add(f"- Python: `{caps.python_version}` on `{caps.platform}`")
    add("")
    add("## Probe results")
    add("")
    add("| Operation | Supported | Evidence / reason |")
    add("|---|---|---|")
    for probe in caps.probes:
        detail = probe.evidence or probe.detail
        detail = detail.replace("|", "\\|")
        if len(detail) > 150:
            detail = detail[:147] + "..."
        add(f"| `{probe.name}` | {_SYMBOL[probe.result]} | {detail} |")
    add("")
    add("## Refresh mechanism")
    add("")
    kind = RefreshKind(caps.refresh_mechanism)
    add(f"**{kind.label}**")
    add("")
    if not kind.is_bootstrapping:
        add(
            "> This backend performs **no CKKS bootstrapping**. The adaptive controller, the "
            "capacity metric and every decision are real, but the primitive that restores "
            "capacity is a client-aided refresh. The dashboard labels it as such on every "
            "screen where it appears."
        )
        add("")
    add("## Notes")
    add("")
    for note in caps.notes:
        add(f"- {note}")
    add("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir", default=str(ROOT / "docs"), help="where to write the generated files"
    )
    args = parser.parse_args()

    print("Probing the installed CKKS library (this performs real key generation)...")
    caps = probe_tenseal(
        CKKSParams(poly_modulus_degree=8192, coeff_mod_bit_sizes=(60, 40, 40, 60), scale_bits=40)
    )

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "LIBRARY_CAPABILITIES.md").write_text(render_markdown(caps), encoding="utf-8")
    (out_dir / "capabilities.json").write_text(
        json.dumps(caps.to_dict(), indent=2), encoding="utf-8"
    )

    width = max(len(p.name) for p in caps.probes)
    for probe in caps.probes:
        detail = probe.evidence or probe.detail
        print(f"  {_SYMBOL[probe.result]:<5} {probe.name:<{width}}  {detail[:88]}")
    print()
    print(f"Refresh mechanism: {RefreshKind(caps.refresh_mechanism).label}")
    print(f"Written: {out_dir / 'LIBRARY_CAPABILITIES.md'}")
    print(f"Written: {out_dir / 'capabilities.json'}")

    if any(p.result is ProbeResult.ERROR for p in caps.probes):
        print("\nAt least one probe ERRORED (not merely unsupported). Investigate before relying")
        print("on results produced by this installation.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
