"""FHE-TrainNet dashboard - Overview.

    streamlit run app/dashboard/Home.py

Section A of the Master Prompt's dashboard requirements: what the project is,
what it is currently configured to do, and - stated before anything else - what
the underlying library can and cannot actually do.
"""

from __future__ import annotations

import json

import streamlit as st

from app.dashboard.common import (
    ROOT,
    fmt,
    metric_note,
    page_setup,
    refresh_banner,
    sidebar_controls,
)
from src.crypto.backend import RefreshKind
from src.data.loader import load_dataset
from src.experiments.registry import list_runs
from src.model.activation import ACTIVATIONS

page_setup("FHE-TrainNet")
st.caption(
    "Adaptive, capacity-aware neural-network training on CKKS-encrypted data - "
    "and an honest account of what that costs."
)

config = sidebar_controls()

st.markdown(
    """
### The problem

A data owner wants a model trained on sensitive records, and does not want the
party doing the training to see them. CKKS makes that possible: the training
engine computes on ciphertexts. The price is that every homomorphic
multiplication consumes part of a finite *modulus chain*, and when it runs out
the ciphertext can no longer be used. Restoring that capacity - bootstrapping,
where the library supports it - is the most expensive operation in the system.

**So when should it happen?** Refresh too often and the cost dominates. Refresh
too late and the computation fails outright. This project implements a fixed
schedule and an adaptive, capacity-aware controller, runs them against the same
workload, and reports what was measured.
"""
)

st.markdown("### What restores that capacity here")
refresh_banner(RefreshKind.CLIENT_AIDED)

col_a, col_b = st.columns([3, 2])

with col_a:
    st.subheader("Current experiment")
    try:
        dataset = load_dataset(config.dataset)
        summary = dataset.summary()
    except Exception as exc:  # noqa: BLE001 - surfaced to the user verbatim
        st.error(f"Dataset could not be loaded: {exc}")
        st.stop()

    params = config.ckks_params()
    budget = config.depth_budget()
    act = ACTIVATIONS.get(config.activation)

    st.table(
        {
            "Setting": [
                "Dataset", "Samples available", "Features", "Class balance",
                "Model", "Activation", "Epochs / batch size / learning rate",
                "FHE scheme", "Ring dimension", "Modulus chain",
                "Multiplicative depth", "Depth per training step", "Steps between refreshes",
                "Modes to run",
            ],
            "Value": [
                f"{summary['name']}",
                str(summary["n_samples"]),
                f"{summary['n_features']} ({', '.join(summary['feature_names'][:4])}"
                f"{', ...' if summary['n_features'] > 4 else ''})",
                json.dumps(summary["class_balance"]),
                "single-layer network, polynomial activation, encrypted weights",
                f"{config.activation} (degree {act.degree if act else '?'}, "
                f"{act.depth_cost if act else '?'} level(s))",
                f"{config.epochs} / {config.batch_size} / {config.learning_rate}",
                "CKKS (Microsoft SEAL via TenSEAL)",
                str(params.poly_modulus_degree),
                str(list(params.coeff_mod_bit_sizes)),
                str(params.max_depth),
                str(budget["depth_per_step"]),
                str(budget["steps_between_refresh"]),
                ", ".join(config.modes),
            ],
        }
    )

with col_b:
    st.subheader("What the library actually supports")
    caps_path = ROOT / "docs" / "capabilities.json"
    if caps_path.exists():
        caps = json.loads(caps_path.read_text(encoding="utf-8"))
        st.caption(
            f"Probed from {caps['library']} {caps['library_version']} - generated by "
            "`scripts/probe_library.py`, not copied from documentation."
        )
        rows = {"Operation": [], "Result": []}
        for probe in caps["probes"]:
            rows["Operation"].append(probe["name"])
            rows["Result"].append(
                {"supported": "yes", "unsupported": "NO", "error": "ERROR"}[probe["result"]]
            )
        st.dataframe(rows, use_container_width=True, height=430, hide_index=True)
    else:
        st.warning(
            "Capability probe has not been run. Execute "
            "`python scripts/probe_library.py` to generate it."
        )

st.divider()
st.subheader("The capacity metric")
metric_note()
st.markdown(
    """
| Indicator | How it is obtained | What it is |
|---|---|---|
| Levels remaining | **derived** | Counted against the modulus chain we configured. Exact, but our arithmetic - so it is cross-checked against the measurement below. |
| Serialized ciphertext size | **measured** | `ciphertext.serialize()` length. Falls one RNS limb per level consumed, which is the library's own account of the ciphertext. |
| Canary precision (bits) | **measured** | A known value carried through the same operations, decrypted and compared with exact arithmetic. Real CKKS approximation error. |

There is no "noise percentage" anywhere in this system, because Microsoft SEAL
exposes no CKKS noise budget and TenSEAL binds no `scale()`, `level()` or
`noise_budget()` accessor. All four were probed; all four raise `AttributeError`.
"""
)

st.divider()
st.subheader("Recent runs")
runs = list_runs()
if not runs:
    st.info(
        "No runs recorded yet. Open **Run Experiment** in the sidebar, or run "
        "`python scripts/run_experiment.py --config configs/demo.yaml`."
    )
else:
    st.dataframe([r.row() for r in runs[:10]], use_container_width=True, hide_index=True)
    st.caption(f"{len(runs)} run(s) stored under `results/`.")
